CREATE TABLE IF NOT EXIST patients (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    patient_number VARCHAR(20) NOT NULL UNIQUE,
    first_name    VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    tc_no               VARCHAR(11) UNIQUE,
    passport_no         VARCHAR(20),
    birth_date          DATE,
    -- gender              VARCHAR(10),
    blood_type          VARCHAR(5),
    phone               VARCHAR(20),
    -- email               VARCHAR(100),
    -- address             TEXT,
    -- city                VARCHAR(50),
    -- country             VARCHAR(50) DEFAULT 'Turkey',
    -- emergency_contact_name        VARCHAR(100),
    -- emergency_contact_phone       VARCHAR(20),
    -- emergency_contact_relation    VARCHAR(50),
    -- allergies           TEXT,
    -- chronic_diseases    TEXT,
    -- insurance_company   VARCHAR(100),
    -- insurance_number    VARCHAR(50),
    notes               TEXT,
    is_active           BOOLEAN DEFAULT TRUE,
    created_by          INTEGER,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);